package com.lmguard.service;

import com.lmguard.dto.inspection.EvidenceResponse;
import com.lmguard.dto.inspection.ExtractedFieldResponse;
import com.lmguard.dto.inspection.InspectionResponse;
import com.lmguard.dto.inspection.ViolationResponse;
import com.lmguard.entity.enums.InspectionStatus;
import com.lmguard.rules.RuleSet;
import com.lmguard.rules.RuleEngineService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Builds the inspection report.
 *
 * <p>The report is returned as structured JSON rather than a rendered PDF. That keeps the
 * backend free of a document toolchain for the MVP and lets the frontend render or print it;
 * a server-side PDF writer can consume exactly this structure later without changing the
 * contract.
 *
 * <p>Two things are always present, whatever the verdict: the exact ruleset version the
 * decision was made under, and a statement that the result is advisory and the enforcement
 * decision belongs to the inspector. A report that omitted either would misrepresent what
 * this system does.
 */
@Service
@RequiredArgsConstructor
public class ReportService {

    private static final String ADVISORY_NOTICE =
            "This report is generated by an automated assistance system. Findings are derived from image "
                    + "analysis evaluated against a fixed, versioned ruleset. Items marked INCONCLUSIVE could "
                    + "not be determined reliably and require manual verification. Nothing in this report "
                    + "constitutes a legal determination; the enforcement decision rests with the "
                    + "authorised Legal Metrology inspector.";

    private final InspectionService inspectionService;
    private final RuleEngineService ruleEngineService;

    @Transactional(readOnly = true)
    public Map<String, Object> buildReport(UUID inspectionId) {
        InspectionResponse inspection = inspectionService.getById(inspectionId);

        Map<String, Object> report = new LinkedHashMap<>();
        report.put("reportType", "LEGAL_METROLOGY_INSPECTION_REPORT");
        report.put("generatedAt", Instant.now());
        report.put("inspectionId", inspection.inspectionId());
        report.put("status", inspection.status());
        report.put("statusMeaning", explain(inspection.status()));
        report.put("rulesetVersion", inspection.rulesetVersion());
        report.put("rulesetNotice", rulesetNotice(inspection.rulesetVersion()));
        report.put("advisoryNotice", ADVISORY_NOTICE);

        report.put("product", inspection.product());
        report.put("inspector", Map.of(
                "id", nullSafe(inspection.inspectorId()),
                "name", nullSafe(inspection.inspectorName())));

        report.put("imageUrl", nullSafe(inspection.imageUrl()));
        report.put("analysisProvider", nullSafe(inspection.aiProvider()));
        report.put("overallConfidence", inspection.overallConfidence());

        report.put("declarations", inspection.fields().stream().map(this::declaration).toList());
        report.put("findings", inspection.violations().stream().map(this::finding).toList());
        report.put("risk", inspection.risk());

        report.put("summary", summary(inspection));
        report.put("createdAt", inspection.createdAt());
        report.put("completedAt", inspection.completedAt());
        return report;
    }

    private Map<String, Object> declaration(ExtractedFieldResponse field) {
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("field", field.name());
        entry.put("declaredValue", field.value() == null ? "NOT DETECTED" : field.value());
        entry.put("confidence", field.confidence());
        entry.put("status", field.status());
        entry.put("region", field.boundingBox());
        return entry;
    }

    private Map<String, Object> finding(ViolationResponse violation) {
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("ruleCode", violation.ruleCode());
        entry.put("field", violation.fieldName());
        entry.put("status", violation.status());
        entry.put("severity", violation.severity());
        entry.put("finding", violation.finding());
        entry.put("remediation", nullSafe(violation.remediation()));
        entry.put("decisionConfidence", violation.decisionConfidence());
        entry.put("observedValue", nullSafe(violation.observedValue()));
        entry.put("evidence", evidence(violation.evidence()));
        return entry;
    }

    private Map<String, Object> evidence(EvidenceResponse evidence) {
        if (evidence == null) {
            return Map.of();
        }
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("imageUrl", nullSafe(evidence.imageUrl()));
        entry.put("x", evidence.x());
        entry.put("y", evidence.y());
        entry.put("width", evidence.width());
        entry.put("height", evidence.height());
        entry.put("ocrConfidence", evidence.ocrConfidence());
        entry.put("description", nullSafe(evidence.description()));
        return entry;
    }

    private Map<String, Object> summary(InspectionResponse inspection) {
        List<ViolationResponse> violations = inspection.violations();
        long nonCompliant = violations.stream()
                .filter(violation -> violation.status() == com.lmguard.entity.enums.ViolationStatus.NON_COMPLIANT)
                .count();
        long inconclusive = violations.size() - nonCompliant;

        Map<String, Object> summary = new LinkedHashMap<>();
        summary.put("declarationsExamined", inspection.fields().size());
        summary.put("nonCompliantFindings", nonCompliant);
        summary.put("inconclusiveFindings", inconclusive);
        summary.put("riskScore", inspection.riskScore());
        summary.put("riskLevel", inspection.riskLevel());
        summary.put("requiresManualVerification", inconclusive > 0
                || inspection.status() == InspectionStatus.INCONCLUSIVE);
        return summary;
    }

    private String rulesetNotice(String version) {
        if (version == null) {
            return "No ruleset was recorded for this inspection; it has not been analysed.";
        }
        try {
            RuleSet ruleSet = ruleEngineService.ruleSet(version);
            if (ruleSet.isSample()) {
                return "Ruleset '%s' is DEMO / SAMPLE scaffolding and is not legally verified. %s"
                        .formatted(version, ruleSet.disclaimer() == null ? "" : ruleSet.disclaimer());
            }
            return "Evaluated against ruleset version '%s'.".formatted(version);
        } catch (RuntimeException ex) {
            return "Evaluated against ruleset version '%s', which is no longer loadable on this server."
                    .formatted(version);
        }
    }

    private String explain(InspectionStatus status) {
        if (status == null) {
            return "Unknown.";
        }
        return switch (status) {
            case COMPLIANT -> "No rule in the applied ruleset was breached with sufficient confidence.";
            case NON_COMPLIANT -> "At least one rule was breached, with confidence above the required threshold.";
            case INCONCLUSIVE -> "The image could not be read reliably enough to decide one or more rules. "
                    + "Manual verification is required. This is NOT a finding of non-compliance.";
            case PENDING -> "The inspection has been opened but not yet analysed.";
            case IN_PROGRESS -> "The inspector is working this case. AI analysis, if run, is advisory "
                    + "only - no final decision has been submitted yet.";
            case PROCESSING -> "Analysis is in progress.";
            case FAILED -> "The analysis pipeline failed. This is a system error, not a compliance verdict.";
        };
    }

    private Object nullSafe(Object value) {
        return value == null ? "" : value;
    }
}
