import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../core/widgets/empty_state.dart';
import '../../../core/widgets/panels.dart';
import '../../../data/models/ai_evaluation.dart';
import '../../../data/models/enums.dart';
import '../../../state/draft_controller.dart';

/// Step 4 — the evidence behind every finding, generated by the AI/rule
/// engine, not captured by the officer. Every violation the rule engine
/// raised is shown against the region of the package photo it was read
/// from; nothing on this screen is typed in or photographed by hand.
class EvidenceStep extends StatefulWidget {
  const EvidenceStep({super.key});

  @override
  State<EvidenceStep> createState() => _EvidenceStepState();
}

class _EvidenceStepState extends State<EvidenceStep> {
  int? _highlighted;

  @override
  Widget build(BuildContext context) {
    final DraftController draft = context.watch<DraftController>();
    final AIEvaluation? evaluation = draft.aiEvaluation;
    final String? imageUrl = evaluation?.packageImageUrl;
    final List<AiViolationEvidence> violations = evaluation?.violations ?? const <AiViolationEvidence>[];

    if (draft.aiStatus == AiEvaluationStatus.processing) {
      return const LoadingState(message: 'Analysing the package photo…');
    }

    if (imageUrl == null) {
      return ListView(
        padding: const EdgeInsets.fromLTRB(16, 16, 16, 24),
        children: <Widget>[
          AppPanel(
            child: EmptyState(
              compact: true,
              icon: Icons.image_search_outlined,
              title: 'No analysis yet',
              message: 'Go back to the scan step and photograph the package - '
                  'evidence is generated automatically once the AI has analysed it.',
            ),
          ),
        ],
      );
    }

    return ListView(
      padding: const EdgeInsets.fromLTRB(16, 16, 16, 24),
      children: <Widget>[
        const InfoBanner(
          message:
              'Each violation below is linked to the exact region of the package '
              'the rule engine flagged. Tap one to highlight it on the photo.',
          icon: Icons.auto_awesome_outlined,
        ),
        const SizedBox(height: 14),
        _AnnotatedImage(
          imageUrl: imageUrl,
          violations: violations,
          highlighted: _highlighted,
        ),
        const SizedBox(height: 18),
        SectionHeading(
          'Violations found',
          trailing: Text('${violations.length}', style: AppText.caption),
        ),
        const SizedBox(height: 10),
        if (violations.isEmpty)
          AppPanel(
            child: const EmptyState(
              compact: true,
              icon: Icons.verified_outlined,
              title: 'No violations detected',
              message: 'The rule engine found every assessable declaration compliant.',
            ),
          )
        else
          ...violations.asMap().entries.map(
                (MapEntry<int, AiViolationEvidence> entry) => _ViolationCard(
                  violation: entry.value,
                  highlighted: _highlighted == entry.key,
                  onTap: () => setState(
                    () => _highlighted = _highlighted == entry.key ? null : entry.key,
                  ),
                ),
              ),
      ],
    );
  }
}

class _AnnotatedImage extends StatefulWidget {
  const _AnnotatedImage({
    required this.imageUrl,
    required this.violations,
    required this.highlighted,
  });

  final String imageUrl;
  final List<AiViolationEvidence> violations;
  final int? highlighted;

  @override
  State<_AnnotatedImage> createState() => _AnnotatedImageState();
}

class _AnnotatedImageState extends State<_AnnotatedImage> {
  ui.Image? _resolved;

  @override
  void initState() {
    super.initState();
    _resolveSize();
  }

  @override
  void didUpdateWidget(_AnnotatedImage oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.imageUrl != widget.imageUrl) {
      _resolved = null;
      _resolveSize();
    }
  }

  void _resolveSize() {
    final ImageStream stream = NetworkImage(widget.imageUrl).resolve(const ImageConfiguration());
    late final ImageStreamListener listener;
    listener = ImageStreamListener((ImageInfo info, bool _) {
      if (mounted) setState(() => _resolved = info.image);
      stream.removeListener(listener);
    }, onError: (Object _, StackTrace? __) {
      stream.removeListener(listener);
    });
    stream.addListener(listener);
  }

  @override
  Widget build(BuildContext context) {
    final ui.Image? natural = _resolved;

    return ClipRRect(
      borderRadius: BorderRadius.circular(8),
      child: AspectRatio(
        aspectRatio: natural == null ? 4 / 3 : natural.width / natural.height,
        child: Stack(
          fit: StackFit.expand,
          children: <Widget>[
            Image.network(
              widget.imageUrl,
              fit: BoxFit.fill,
              loadingBuilder: (BuildContext context, Widget child, ImageChunkEvent? progress) =>
                  progress == null
                      ? child
                      : Container(color: AppColors.navy, child: const Center(
                          child: CircularProgressIndicator(
                            strokeWidth: 2.4,
                            valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                          ),
                        )),
              errorBuilder: (_, __, ___) => Container(
                color: AppColors.navy,
                alignment: Alignment.center,
                child: const Icon(Icons.broken_image_outlined, color: Colors.white54),
              ),
            ),
            if (natural != null)
              CustomPaint(
                painter: _BoxesPainter(
                  violations: widget.violations,
                  naturalWidth: natural.width.toDouble(),
                  naturalHeight: natural.height.toDouble(),
                  highlighted: widget.highlighted,
                ),
              ),
          ],
        ),
      ),
    );
  }
}

class _BoxesPainter extends CustomPainter {
  _BoxesPainter({
    required this.violations,
    required this.naturalWidth,
    required this.naturalHeight,
    required this.highlighted,
  });

  final List<AiViolationEvidence> violations;
  final double naturalWidth;
  final double naturalHeight;
  final int? highlighted;

  @override
  void paint(Canvas canvas, Size size) {
    final double scaleX = size.width / naturalWidth;
    final double scaleY = size.height / naturalHeight;

    for (int i = 0; i < violations.length; i++) {
      final AiBoundingBox? box = violations[i].boundingBox;
      if (box == null) continue;

      final bool active = highlighted == i;
      final Rect rect = Rect.fromLTWH(
        box.x * scaleX,
        box.y * scaleY,
        box.width * scaleX,
        box.height * scaleY,
      );
      final Color color = active ? AppColors.accent : AppColors.danger;

      canvas.drawRect(
        rect,
        Paint()
          ..color = color
          ..style = PaintingStyle.stroke
          ..strokeWidth = active ? 3 : 2,
      );
      if (active) {
        canvas.drawRect(rect, Paint()..color = color.withOpacity(0.15));
      }
    }
  }

  @override
  bool shouldRepaint(covariant _BoxesPainter oldDelegate) =>
      oldDelegate.violations != violations || oldDelegate.highlighted != highlighted;
}

class _ViolationCard extends StatelessWidget {
  const _ViolationCard({
    required this.violation,
    required this.highlighted,
    required this.onTap,
  });

  final AiViolationEvidence violation;
  final bool highlighted;
  final VoidCallback onTap;

  Color get _severityColor {
    switch (violation.severity) {
      case 'CRITICAL':
        return AppColors.critical;
      case 'MAJOR':
        return AppColors.danger;
      default:
        return AppColors.warning;
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppPanel(
      margin: const EdgeInsets.only(bottom: 10),
      onTap: onTap,
      leadingStripe: _severityColor,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Expanded(child: Text(violation.ruleCode, style: AppText.identifier)),
              if (violation.boundingBox == null)
                Text('No region on package', style: AppText.caption.copyWith(color: AppColors.inkFaint))
              else
                Icon(
                  highlighted ? Icons.visibility : Icons.crop_free,
                  size: 16,
                  color: highlighted ? AppColors.accent : AppColors.inkFaint,
                ),
            ],
          ),
          const SizedBox(height: 6),
          Text(violation.fieldName, style: AppText.recordTitle),
          const SizedBox(height: 6),
          Text(violation.finding, style: AppText.body),
          if (violation.remediation != null) ...<Widget>[
            const SizedBox(height: 8),
            Text(
              violation.remediation!,
              style: AppText.caption.copyWith(fontStyle: FontStyle.italic),
            ),
          ],
          const SizedBox(height: 8),
          Text(
            'Confidence ${(violation.confidence * 100).round()}%',
            style: AppText.caption.copyWith(color: AppColors.inkMuted),
          ),
        ],
      ),
    );
  }
}
